version: 2

updates:
  - package-ecosystem: docker-compose
    directory: "/"
    schedule:
      interval: weekly
      day: monday
    groups:
      docker:
        patterns:
          - '*'

  - package-ecosystem: github-actions
    directories:
      - "/"
      - "/.github/actions/**"
    schedule:
      interval: weekly
      day: monday
    groups:
      gha:
        patterns:
          - '*'
