services:
  aiostreams:
    container_name: aiostreams
    image: ghcr.io/viren070/aiostreams:v2.15.4
    restart: unless-stopped
    environment:
      BASE_URL: https://aiostreams.kswb.dev
      DISABLE_RATE_LIMITS: true
      REGEX_FILTER_ACCESS: all
      SECRET_KEY: $AIOSTREAMS_SECRET_KEY
    volumes:
      - /home/pi/docker/aiostreams/data:/app/data

  # bumper:
  #   container_name: bumper
  #   image: ghcr.io/mvladislav/bumper:sha-a39a705
  #   restart: unless-stopped
  #   platform: linux/arm64

  cloudflared:
    container_name: cloudflared
    image: cloudflare/cloudflared:2025.10.0
    restart: unless-stopped
    command: tunnel run
    environment:
      TUNNEL_TOKEN: $CLOUDFLARED_TUNNEL_TOKEN
    extra_hosts:
      - host.docker.internal:host-gateway

  # hcpy:
  #   container_name: hcpy
  #   image: ghcr.io/hcpy2-0/hcpy:v0.1.6
  #   restart: unless-stopped
  #   command: /app/hc-login.py "$HC_USERNAME" "$HC_PASSWORD" config/devices.json
  #   volumes:
  #     - /home/pi/docker/hcpy/config:/app/config

  home-assistant:
    container_name: home-assistant
    image: ghcr.io/home-assistant/home-assistant:2025.10.3
    restart: unless-stopped
    privileged: true
    network_mode: host
    volumes:
      - /home/pi/docker/home-assistant/config:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro

  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto:2.0.22
    restart: unless-stopped
    ports:
        - 1883:1883
        - 1884:1884
    environment:
      - HA_CONFIG_MQTT_USER
      - HA_CONFIG_MQTT_PASSWORD
      - ZIGBEE2MQTT_CONFIG_MQTT_USER
      - ZIGBEE2MQTT_CONFIG_MQTT_PASSWORD
    volumes:
      - /home/pi/docker/mosquitto/config:/mosquitto/config
      - /home/pi/docker/mosquitto/data:/mosquitto/data
      - /home/pi/docker/mosquitto/log:/mosquitto/log
      - /home/pi/docker/mosquitto/entrypoint.sh:/docker-entrypoint.sh

  music-assistant-server:
    container_name: music-assistant-server
    image: ghcr.io/music-assistant/server:2.6.0
    restart: unless-stopped
    # Network mode must be set to host for MA to work correctly
    network_mode: host
    volumes:
      - /home/pi/docker/music-assistant-server/data:/data/
    # privileged caps (and security-opt) needed to mount smb folders within the container
    cap_add:
      - SYS_ADMIN
      - DAC_READ_SEARCH
    security_opt:
      - apparmor:unconfined
    environment:
      # Provide logging level as environment variable.
      # default=info, possible=(critical, error, warning, info, debug)
      - LOG_LEVEL=info

  zigbee2mqtt:
    container_name: zigbee2mqtt
    image: ghcr.io/koenkk/zigbee2mqtt:2.6.2
    restart: unless-stopped
    volumes:
      - /home/pi/docker/zigbee2mqtt/data:/app/data
      - /run/udev:/run/udev:ro
    environment:
      - ZIGBEE2MQTT_CONFIG_MQTT_USER
      - ZIGBEE2MQTT_CONFIG_MQTT_PASSWORD
      - TZ=Europe/London
    devices:
      # Make sure this matched your adapter location
      - /dev/serial/by-id/usb-Nabu_Casa_Home_Assistant_Connect_ZBT-1_eea67b52ae39ef119e3e57f454516304-if00-port0:/dev/ttyUSB0
