homeassistant: true
frontend: true
mqtt:
  base_topic: zigbee2mqtt
  server: mqtt://mosquitto
serial:
  adapter: ember
  port: /dev/ttyUSB0
  baudrate: 115200
  rtscts: true
advanced:
  network_key:
    - 203
    - 30
    - 235
    - 175
    - 185
    - 197
    - 165
    - 4
    - 150
    - 235
    - 215
    - 180
    - 49
    - 207
    - 141
    - 217
  pan_id: 62763
  ext_pan_id:
    - 110
    - 25
    - 118
    - 138
    - 29
    - 64
    - 152
    - 41
  homeassistant_legacy_entity_attributes: false
  legacy_api: false
  legacy_availability_payload: false
device_options:
  legacy: false
